### ISSUE TITLE
can't call $ foreman run python3 manage.py migrate

### ISSUE THREAD

**Issue by futuretekag** [blockcypher/explorer#180]
Can't call the create tables command with the current version on master branch.
`
WARNING: without a POSTMARK_API_KEY you cannot send emails
## WARNING: without a WEBHOOK_SECRET_KEY you cannot receive webhooks

SITE_DOMAIN is set to bc.ngrok.com
## If you're using webhooks locally, be sure this is correct

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/**init**.py", line 18, in setup
    from django.utils.log import configure_logging
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/utils/log.py", line 13, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_filter
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/views/debug.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/http/**init**.py", line 4, in <module>
    from django.http.response import (HttpResponse, StreamingHttpResponse,
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/core/serializers/**init**.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/db/models/**init**.py", line 6, in <module>
    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/db/models/query.py", line 13, in <module>
    from django.db.models.fields import AutoField, Empty
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/db/models/fields/**init**.py", line 18, in <module>
    from django import forms
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/forms/**init**.py", line 6, in <module>
    from django.forms.fields import \*  # NOQA
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/forms/fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/forms/utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "/home/blockchain/explorer/venv/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'

`

Thx for any help.

**Comment by Alex-Werner** [comment]
Got the issue. 
Fixed it by downgrading python3 (3.5.2) to python3.3 (do not go under 3.3 nor after 3.5).

`Mind about apt-get install python3.3-dev`

`virtualenv -p python3.3 venv`
