### ISSUE TITLE
Error while installing requirements..

### ISSUE THREAD

**Issue by systemroot** [blockcypher/explorer#195]
hi,

When i tried `pip3 install -r requirements.txt`
i got this output 
```bash
Command /hostdata/explorer.sick.al/explorer/venv/bin/python3 -c "import setuptools, tokenize;__file__='/hostdata/explorer.sick.al/explorer/venv/build/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sz_k_dm8-record/install-record.txt --single-version-externally-managed --compile --install-headers /hostdata/explorer.sick.al/explorer/venv/include/site/python3.4 failed with error code 1 in /hostdata/explorer.sick.al/explorer/venv/build/gnureadline
Storing debug log for failure in /root/.pip/pip.log
```

from the log file i can read this
```bash
creating build/temp.linux-x86_64-3.4/Modules

creating build/temp.linux-x86_64-3.4/Modules/3.4

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -I. -I/usr/include/python3.4m -c Modules/3.4/readline.c -o build/temp.linux-x86_64-3.4/Modules/3.4/readline.o

In file included from Modules/3.4/readline.c:32:0:

./readline/readline.h:385:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]

 extern int rl_message ();

 ^

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/Modules/3.4/readline.o readline/libreadline.a readline/libhistory.a -lncurses -o build/lib.linux-x86_64-3.4/gnureadline.cpython-34m.so

/usr/bin/ld: cannot find -lncurses

collect2: error: ld returned 1 exit status

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bjq99j24-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/gnureadline
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bjq99j24-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/gnureadline
```

seems to be a problem with `ld` ?! I'm using ubuntu 14.04. can anyone help about this problem?!
Thanks!

**Comment by systemroot** [comment]
```bash apt-get install libncurses5-dev``` and problem solved.
