### ISSUE TITLE
HTMLParseError = _html_parser.HTMLParseError

### ISSUE THREAD

**Issue by cryptozeny** [blockcypher/explorer#240]
Hi,

i've got this error. when i run this:

> $ foreman run python3 manage.py migrate
> ...
> File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module>
>     from .html_parser import HTMLParser, HTMLParseError
>   File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module>
>     HTMLParseError = _html_parser.HTMLParseError
> AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
> 

ERROR LOG:
```
(venv) kim@computer:~/git/explorer$ foreman run python3 manage.py migrate
WARNING: without a POSTMARK_API_KEY you cannot send emails
WARNING: without a WEBHOOK_SECRET_KEY you cannot receive webhooks
---------------------------------------------------------------------------
SITE_DOMAIN is set to anzucoin.ngrok.com
If you're using webhooks locally, be sure this is correct
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    from django.utils.log import configure_logging
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/utils/log.py", line 13, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_filter
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/views/debug.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/http/__init__.py", line 4, in <module>
    from django.http.response import (HttpResponse, StreamingHttpResponse,
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/db/models/__init__.py", line 6, in <module>
    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/db/models/query.py", line 13, in <module>
    from django.db.models.fields import AutoField, Empty
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 18, in <module>
    from django import forms
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/forms/__init__.py", line 6, in <module>
    from django.forms.fields import *  # NOQA
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/forms/fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/forms/utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "/home/ak/git/explorer/venv/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'
(venv) kim@computer:~/git/explorer$
```

Any suggest? Thanks in advanced

**Comment by makeholer** [comment]
To fix this just delete the text 'HTMLParseError' from the files...
